version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  web:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - db
